### ISSUE TITLE
Global config option for baseline/storage location don't take

### ISSUE THREAD

**Issue by sp3nx0r** [Yelp/detect-secrets-server#43]
Noticed that setting a global config for baseline doesn't actually take. CLI and per-repo YAML config work fine. Below example config doesn't actually work.

```
default:
  plugins:
    HexHighEntropyString: 3
    Base64HighEntropyString: 4.5
    PrivateKeyDetector: true
 baseline: .secrets.baseline
 base_temp_dir: /some/path/to/store
  
```
In spite of code documentation which suggests that it should: https://github.com/Yelp/detect-secrets-server/blob/e9f60d683d816d02d740f25fa1799a2a755c9cb3/detect_secrets_server/actions/initialize.py#L81-L82

Doesn't work if this YAML index is baseline or baseline_filename (which is what it ends up saved as in the tracked JSON). 

Likely root cause is because baseline isn't taken into consideration in `def apply_default_plugin_options_to_repos()`or similar function. Same applies for storage location `base_temp_dir`.
